### ISSUE TITLE
合并 ipc,task,common 的文档到 mi_dev 分支

### ISSUE THREAD

**Issue by yfblock** [rel4team/rel4_kernel#25]
合并kern-crates的仓库文档到这个仓库

**Comment by Huzhiwen1208** [comment]
> 合并kern-crates的仓库文档到这个仓库

[MR]: https://github.com/rel4team/rel4_kernel/pull/28

**Comment by yfblock** [comment]
This task was completed at https://github.com/rel4team/rel4_kernel/pull/28.
